AllCops:
  Exclude:
    - xlog.gemspec
    - spec/**/*.rb
    - spec/*.rb

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/ParameterLists:
  Max: 6

Metrics/MethodLength:
  Max: 15

Naming/MethodParameterName:
  Enabled: false  

Metrics/AbcSize:
  Max: 17